
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type CombatConst struct {
    Key string
    Category string
    ValueType string
    Value string
    MinValue string
    MaxValue string
    Unit string
    Description string
}

const TypeId_CombatConst = -1642321745

func (*CombatConst) GetTypeId() int32 {
    return -1642321745
}

func NewCombatConst(_buf map[string]interface{}) (_v *CombatConst, err error) {
    _v = &CombatConst{}
    { var _ok_ bool; var __json_key__ interface{}; if __json_key__, _ok_ = _buf["key"]; !_ok_ || __json_key__ == nil { err = errors.New("key error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_key__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Key = __x__ }}
    { var _ok_ bool; var __json_category__ interface{}; if __json_category__, _ok_ = _buf["category"]; !_ok_ || __json_category__ == nil { err = errors.New("category error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_category__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Category = __x__ }}
    { var _ok_ bool; var __json_value_type__ interface{}; if __json_value_type__, _ok_ = _buf["value_type"]; !_ok_ || __json_value_type__ == nil { err = errors.New("value_type error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_value_type__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ValueType = __x__ }}
    { var _ok_ bool; var __json_value__ interface{}; if __json_value__, _ok_ = _buf["value"]; !_ok_ || __json_value__ == nil { err = errors.New("value error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_value__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Value = __x__ }}
    { var _ok_ bool; var __json_min_value__ interface{}; if __json_min_value__, _ok_ = _buf["min_value"]; !_ok_ || __json_min_value__ == nil { err = errors.New("min_value error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_min_value__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.MinValue = __x__ }}
    { var _ok_ bool; var __json_max_value__ interface{}; if __json_max_value__, _ok_ = _buf["max_value"]; !_ok_ || __json_max_value__ == nil { err = errors.New("max_value error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_max_value__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.MaxValue = __x__ }}
    { var _ok_ bool; var __json_unit__ interface{}; if __json_unit__, _ok_ = _buf["unit"]; !_ok_ || __json_unit__ == nil { err = errors.New("unit error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_unit__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Unit = __x__ }}
    { var _ok_ bool; var __json_description__ interface{}; if __json_description__, _ok_ = _buf["description"]; !_ok_ || __json_description__ == nil { err = errors.New("description error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_description__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Description = __x__ }}
    return
}

