//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type EncounterModifier struct {
	Id         string
	ScenarioId string
	Factor     string
	Side       string
	Attribute  string
	Weight     int32
	ReasonCode string
}

const TypeId_EncounterModifier = 1743793418

func (*EncounterModifier) GetTypeId() int32 {
	return 1743793418
}

func NewEncounterModifier(_buf map[string]interface{}) (_v *EncounterModifier, err error) {
	_v = &EncounterModifier{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_scenario_id__ interface{}
		if __json_scenario_id__, _ok_ = _buf["scenario_id"]; !_ok_ || __json_scenario_id__ == nil {
			err = errors.New("scenario_id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_scenario_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.ScenarioId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_factor__ interface{}
		if __json_factor__, _ok_ = _buf["factor"]; !_ok_ || __json_factor__ == nil {
			err = errors.New("factor error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_factor__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Factor = __x__
		}
	}
	{
		var _ok_ bool
		var __json_side__ interface{}
		if __json_side__, _ok_ = _buf["side"]; !_ok_ || __json_side__ == nil {
			err = errors.New("side error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_side__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Side = __x__
		}
	}
	{
		var _ok_ bool
		var __json_attribute__ interface{}
		if __json_attribute__, _ok_ = _buf["attribute"]; !_ok_ || __json_attribute__ == nil {
			err = errors.New("attribute error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_attribute__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Attribute = __x__
		}
	}
	{
		var _ok_ bool
		var __json_weight__ interface{}
		if __json_weight__, _ok_ = _buf["weight"]; !_ok_ || __json_weight__ == nil {
			err = errors.New("weight error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_weight__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Weight = __x__
		}
	}
	{
		var _ok_ bool
		var __json_reason_code__ interface{}
		if __json_reason_code__, _ok_ = _buf["reason_code"]; !_ok_ || __json_reason_code__ == nil {
			err = errors.New("reason_code error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_reason_code__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.ReasonCode = __x__
		}
	}
	return
}
