//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type MapEdge struct {
	Id             string
	FromNode       string
	ToNode         string
	BaseTime       int32
	StaminaCost    int32
	Risk           int32
	Noise          int32
	RiskPoints     []string
	InterceptNodes []string
	Bidirectional  bool
}

const TypeId_MapEdge = -1794043623

func (*MapEdge) GetTypeId() int32 {
	return -1794043623
}

func NewMapEdge(_buf map[string]interface{}) (_v *MapEdge, err error) {
	_v = &MapEdge{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_from_node__ interface{}
		if __json_from_node__, _ok_ = _buf["from_node"]; !_ok_ || __json_from_node__ == nil {
			err = errors.New("from_node error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_from_node__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.FromNode = __x__
		}
	}
	{
		var _ok_ bool
		var __json_to_node__ interface{}
		if __json_to_node__, _ok_ = _buf["to_node"]; !_ok_ || __json_to_node__ == nil {
			err = errors.New("to_node error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_to_node__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.ToNode = __x__
		}
	}
	{
		var _ok_ bool
		var __json_base_time__ interface{}
		if __json_base_time__, _ok_ = _buf["base_time"]; !_ok_ || __json_base_time__ == nil {
			err = errors.New("base_time error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_base_time__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.BaseTime = __x__
		}
	}
	{
		var _ok_ bool
		var __json_stamina_cost__ interface{}
		if __json_stamina_cost__, _ok_ = _buf["stamina_cost"]; !_ok_ || __json_stamina_cost__ == nil {
			err = errors.New("stamina_cost error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_stamina_cost__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.StaminaCost = __x__
		}
	}
	{
		var _ok_ bool
		var __json_risk__ interface{}
		if __json_risk__, _ok_ = _buf["risk"]; !_ok_ || __json_risk__ == nil {
			err = errors.New("risk error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_risk__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Risk = __x__
		}
	}
	{
		var _ok_ bool
		var __json_noise__ interface{}
		if __json_noise__, _ok_ = _buf["noise"]; !_ok_ || __json_noise__ == nil {
			err = errors.New("noise error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_noise__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Noise = __x__
		}
	}
	{
		var _ok_ bool
		var __json_risk_points__ interface{}
		if __json_risk_points__, _ok_ = _buf["risk_points"]; !_ok_ || __json_risk_points__ == nil {
			err = errors.New("risk_points error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_risk_points__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.RiskPoints = __x__
		}
	}
	{
		var _ok_ bool
		var __json_intercept_nodes__ interface{}
		if __json_intercept_nodes__, _ok_ = _buf["intercept_nodes"]; !_ok_ || __json_intercept_nodes__ == nil {
			err = errors.New("intercept_nodes error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_intercept_nodes__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.InterceptNodes = __x__
		}
	}
	{
		var _ok_ bool
		var __json_bidirectional__ interface{}
		if __json_bidirectional__, _ok_ = _buf["bidirectional"]; !_ok_ || __json_bidirectional__ == nil {
			err = errors.New("bidirectional error")
			return
		} else {
			var __x__ bool
			{
				var _ok_ bool
				if __x__, _ok_ = __json_bidirectional__.(bool); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Bidirectional = __x__
		}
	}
	return
}
