
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type MapNode struct {
    Id string
    MapId string
    Name string
    Zone string
    Site string
    NodeType string
    DefaultSide string
    X float32
    Y float32
    Floor string
    AreaUsages []string
    Shape string
    Radius float32
    Points string
}

const TypeId_MapNode = -1793765026

func (*MapNode) GetTypeId() int32 {
    return -1793765026
}

func NewMapNode(_buf map[string]interface{}) (_v *MapNode, err error) {
    _v = &MapNode{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_map_id__ interface{}; if __json_map_id__, _ok_ = _buf["map_id"]; !_ok_ || __json_map_id__ == nil { err = errors.New("map_id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_map_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.MapId = __x__ }}
    { var _ok_ bool; var __json_name__ interface{}; if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil { err = errors.New("name error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_name__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Name = __x__ }}
    { var _ok_ bool; var __json_zone__ interface{}; if __json_zone__, _ok_ = _buf["zone"]; !_ok_ || __json_zone__ == nil { err = errors.New("zone error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_zone__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Zone = __x__ }}
    { var _ok_ bool; var __json_site__ interface{}; if __json_site__, _ok_ = _buf["site"]; !_ok_ || __json_site__ == nil { err = errors.New("site error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_site__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Site = __x__ }}
    { var _ok_ bool; var __json_node_type__ interface{}; if __json_node_type__, _ok_ = _buf["node_type"]; !_ok_ || __json_node_type__ == nil { err = errors.New("node_type error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_node_type__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.NodeType = __x__ }}
    { var _ok_ bool; var __json_default_side__ interface{}; if __json_default_side__, _ok_ = _buf["default_side"]; !_ok_ || __json_default_side__ == nil { err = errors.New("default_side error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_default_side__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.DefaultSide = __x__ }}
    { var _ok_ bool; var __json_x__ interface{}; if __json_x__, _ok_ = _buf["x"]; !_ok_ || __json_x__ == nil { err = errors.New("x error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_x__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.X = __x__ }}
    { var _ok_ bool; var __json_y__ interface{}; if __json_y__, _ok_ = _buf["y"]; !_ok_ || __json_y__ == nil { err = errors.New("y error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_y__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Y = __x__ }}
    { var _ok_ bool; var __json_floor__ interface{}; if __json_floor__, _ok_ = _buf["floor"]; !_ok_ || __json_floor__ == nil { err = errors.New("floor error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_floor__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Floor = __x__ }}
    { var _ok_ bool; var __json_area_usages__ interface{}; if __json_area_usages__, _ok_ = _buf["area_usages"]; !_ok_ || __json_area_usages__ == nil { err = errors.New("area_usages error"); return } else { var __x__ []string;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_area_usages__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]string, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ string
                        {  if _list_v0_, _ok_ = _e0_.(string); !_ok_ { err = errors.New("_list_v0_ error"); return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.AreaUsages = __x__ }}
    { var _ok_ bool; var __json_shape__ interface{}; if __json_shape__, _ok_ = _buf["shape"]; !_ok_ || __json_shape__ == nil { err = errors.New("shape error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_shape__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Shape = __x__ }}
    { var _ok_ bool; var __json_radius__ interface{}; if __json_radius__, _ok_ = _buf["radius"]; !_ok_ || __json_radius__ == nil { err = errors.New("radius error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_radius__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Radius = __x__ }}
    { var _ok_ bool; var __json_points__ interface{}; if __json_points__, _ok_ = _buf["points"]; !_ok_ || __json_points__ == nil { err = errors.New("points error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_points__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Points = __x__ }}
    return
}

