//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type MapTag struct {
	Id          string
	MapId       string
	Category    string
	Value       string
	Side        string
	Weight      int32
	ReasonCode  string
	Description string
}

const TypeId_MapTag = -1997520706

func (*MapTag) GetTypeId() int32 {
	return -1997520706
}

func NewMapTag(_buf map[string]interface{}) (_v *MapTag, err error) {
	_v = &MapTag{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_map_id__ interface{}
		if __json_map_id__, _ok_ = _buf["map_id"]; !_ok_ || __json_map_id__ == nil {
			err = errors.New("map_id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_map_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.MapId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_category__ interface{}
		if __json_category__, _ok_ = _buf["category"]; !_ok_ || __json_category__ == nil {
			err = errors.New("category error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_category__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Category = __x__
		}
	}
	{
		var _ok_ bool
		var __json_value__ interface{}
		if __json_value__, _ok_ = _buf["value"]; !_ok_ || __json_value__ == nil {
			err = errors.New("value error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_value__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Value = __x__
		}
	}
	{
		var _ok_ bool
		var __json_side__ interface{}
		if __json_side__, _ok_ = _buf["side"]; !_ok_ || __json_side__ == nil {
			err = errors.New("side error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_side__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Side = __x__
		}
	}
	{
		var _ok_ bool
		var __json_weight__ interface{}
		if __json_weight__, _ok_ = _buf["weight"]; !_ok_ || __json_weight__ == nil {
			err = errors.New("weight error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_weight__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Weight = __x__
		}
	}
	{
		var _ok_ bool
		var __json_reason_code__ interface{}
		if __json_reason_code__, _ok_ = _buf["reason_code"]; !_ok_ || __json_reason_code__ == nil {
			err = errors.New("reason_code error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_reason_code__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.ReasonCode = __x__
		}
	}
	{
		var _ok_ bool
		var __json_description__ interface{}
		if __json_description__, _ok_ = _buf["description"]; !_ok_ || __json_description__ == nil {
			err = errors.New("description error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_description__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Description = __x__
		}
	}
	return
}
