//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type Player struct {
	Id          string
	Name        string
	Team        string
	Nationality string
	Entry       int32
	Aim         int32
	Trade       int32
	Clutch      int32
	Firepower   int32
	Gamesense   int32
	Reaction    int32
	Positioning int32
	Awareness   int32
	Teamplay    int32
	Utility     int32
	Composure   int32
	Mobility    int32
	Endurance   int32
	Discipline  int32
	Positions   []string
	Rarity      string
	Portrait    string
}

const TypeId_Player = -1901885695

func (*Player) GetTypeId() int32 {
	return -1901885695
}

func NewPlayer(_buf map[string]interface{}) (_v *Player, err error) {
	_v = &Player{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_name__ interface{}
		if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil {
			err = errors.New("name error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_name__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Name = __x__
		}
	}
	{
		var _ok_ bool
		var __json_team__ interface{}
		if __json_team__, _ok_ = _buf["team"]; !_ok_ || __json_team__ == nil {
			err = errors.New("team error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_team__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Team = __x__
		}
	}
	{
		var _ok_ bool
		var __json_nationality__ interface{}
		if __json_nationality__, _ok_ = _buf["nationality"]; !_ok_ || __json_nationality__ == nil {
			err = errors.New("nationality error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_nationality__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Nationality = __x__
		}
	}
	{
		var _ok_ bool
		var __json_entry__ interface{}
		if __json_entry__, _ok_ = _buf["entry"]; !_ok_ || __json_entry__ == nil {
			err = errors.New("entry error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_entry__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Entry = __x__
		}
	}
	{
		var _ok_ bool
		var __json_aim__ interface{}
		if __json_aim__, _ok_ = _buf["aim"]; !_ok_ || __json_aim__ == nil {
			err = errors.New("aim error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_aim__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Aim = __x__
		}
	}
	{
		var _ok_ bool
		var __json_trade__ interface{}
		if __json_trade__, _ok_ = _buf["trade"]; !_ok_ || __json_trade__ == nil {
			err = errors.New("trade error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_trade__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Trade = __x__
		}
	}
	{
		var _ok_ bool
		var __json_clutch__ interface{}
		if __json_clutch__, _ok_ = _buf["clutch"]; !_ok_ || __json_clutch__ == nil {
			err = errors.New("clutch error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_clutch__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Clutch = __x__
		}
	}
	{
		var _ok_ bool
		var __json_firepower__ interface{}
		if __json_firepower__, _ok_ = _buf["firepower"]; !_ok_ || __json_firepower__ == nil {
			err = errors.New("firepower error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_firepower__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Firepower = __x__
		}
	}
	{
		var _ok_ bool
		var __json_gamesense__ interface{}
		if __json_gamesense__, _ok_ = _buf["gamesense"]; !_ok_ || __json_gamesense__ == nil {
			err = errors.New("gamesense error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_gamesense__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Gamesense = __x__
		}
	}
	{
		var _ok_ bool
		var __json_reaction__ interface{}
		if __json_reaction__, _ok_ = _buf["reaction"]; !_ok_ || __json_reaction__ == nil {
			err = errors.New("reaction error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_reaction__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Reaction = __x__
		}
	}
	{
		var _ok_ bool
		var __json_positioning__ interface{}
		if __json_positioning__, _ok_ = _buf["positioning"]; !_ok_ || __json_positioning__ == nil {
			err = errors.New("positioning error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_positioning__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Positioning = __x__
		}
	}
	{
		var _ok_ bool
		var __json_awareness__ interface{}
		if __json_awareness__, _ok_ = _buf["awareness"]; !_ok_ || __json_awareness__ == nil {
			err = errors.New("awareness error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_awareness__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Awareness = __x__
		}
	}
	{
		var _ok_ bool
		var __json_teamplay__ interface{}
		if __json_teamplay__, _ok_ = _buf["teamplay"]; !_ok_ || __json_teamplay__ == nil {
			err = errors.New("teamplay error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_teamplay__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Teamplay = __x__
		}
	}
	{
		var _ok_ bool
		var __json_utility__ interface{}
		if __json_utility__, _ok_ = _buf["utility"]; !_ok_ || __json_utility__ == nil {
			err = errors.New("utility error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_utility__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Utility = __x__
		}
	}
	{
		var _ok_ bool
		var __json_composure__ interface{}
		if __json_composure__, _ok_ = _buf["composure"]; !_ok_ || __json_composure__ == nil {
			err = errors.New("composure error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_composure__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Composure = __x__
		}
	}
	{
		var _ok_ bool
		var __json_mobility__ interface{}
		if __json_mobility__, _ok_ = _buf["mobility"]; !_ok_ || __json_mobility__ == nil {
			err = errors.New("mobility error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_mobility__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Mobility = __x__
		}
	}
	{
		var _ok_ bool
		var __json_endurance__ interface{}
		if __json_endurance__, _ok_ = _buf["endurance"]; !_ok_ || __json_endurance__ == nil {
			err = errors.New("endurance error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_endurance__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Endurance = __x__
		}
	}
	{
		var _ok_ bool
		var __json_discipline__ interface{}
		if __json_discipline__, _ok_ = _buf["discipline"]; !_ok_ || __json_discipline__ == nil {
			err = errors.New("discipline error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_discipline__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Discipline = __x__
		}
	}
	{
		var _ok_ bool
		var __json_positions__ interface{}
		if __json_positions__, _ok_ = _buf["positions"]; !_ok_ || __json_positions__ == nil {
			err = errors.New("positions error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_positions__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.Positions = __x__
		}
	}
	{
		var _ok_ bool
		var __json_rarity__ interface{}
		if __json_rarity__, _ok_ = _buf["rarity"]; !_ok_ || __json_rarity__ == nil {
			err = errors.New("rarity error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_rarity__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Rarity = __x__
		}
	}
	{
		var _ok_ bool
		var __json_portrait__ interface{}
		if __json_portrait__, _ok_ = _buf["portrait"]; !_ok_ || __json_portrait__ == nil {
			err = errors.New("portrait error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_portrait__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Portrait = __x__
		}
	}
	return
}
