//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type RouteTemplate struct {
	Id               string
	MapId            string
	Side             string
	TargetSite       string
	Tempo            string
	RecommendedMin   int32
	RecommendedMax   int32
	RequiredRoles    []string
	KeyAttributes    string
	RouteIds         []string
	RouteAllocations map[string]int32
	ScenarioIds      []string
	MapTagIds        []string
	CommonCtSetupIds []string
	SuccessNextPhase string
	FailureFallbacks []string
}

const TypeId_RouteTemplate = -1377781309

func (*RouteTemplate) GetTypeId() int32 {
	return -1377781309
}

func NewRouteTemplate(_buf map[string]interface{}) (_v *RouteTemplate, err error) {
	_v = &RouteTemplate{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_map_id__ interface{}
		if __json_map_id__, _ok_ = _buf["map_id"]; !_ok_ || __json_map_id__ == nil {
			err = errors.New("map_id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_map_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.MapId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_side__ interface{}
		if __json_side__, _ok_ = _buf["side"]; !_ok_ || __json_side__ == nil {
			err = errors.New("side error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_side__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Side = __x__
		}
	}
	{
		var _ok_ bool
		var __json_target_site__ interface{}
		if __json_target_site__, _ok_ = _buf["target_site"]; !_ok_ || __json_target_site__ == nil {
			err = errors.New("target_site error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_target_site__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.TargetSite = __x__
		}
	}
	{
		var _ok_ bool
		var __json_tempo__ interface{}
		if __json_tempo__, _ok_ = _buf["tempo"]; !_ok_ || __json_tempo__ == nil {
			err = errors.New("tempo error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_tempo__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Tempo = __x__
		}
	}
	{
		var _ok_ bool
		var __json_recommended_min__ interface{}
		if __json_recommended_min__, _ok_ = _buf["recommended_min"]; !_ok_ || __json_recommended_min__ == nil {
			err = errors.New("recommended_min error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_recommended_min__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.RecommendedMin = __x__
		}
	}
	{
		var _ok_ bool
		var __json_recommended_max__ interface{}
		if __json_recommended_max__, _ok_ = _buf["recommended_max"]; !_ok_ || __json_recommended_max__ == nil {
			err = errors.New("recommended_max error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_recommended_max__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.RecommendedMax = __x__
		}
	}
	{
		var _ok_ bool
		var __json_required_roles__ interface{}
		if __json_required_roles__, _ok_ = _buf["required_roles"]; !_ok_ || __json_required_roles__ == nil {
			err = errors.New("required_roles error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_required_roles__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.RequiredRoles = __x__
		}
	}
	{
		var _ok_ bool
		var __json_key_attributes__ interface{}
		if __json_key_attributes__, _ok_ = _buf["key_attributes"]; !_ok_ || __json_key_attributes__ == nil {
			err = errors.New("key_attributes error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_key_attributes__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.KeyAttributes = __x__
		}
	}
	{
		var _ok_ bool
		var __json_route_ids__ interface{}
		if __json_route_ids__, _ok_ = _buf["route_ids"]; !_ok_ || __json_route_ids__ == nil {
			err = errors.New("route_ids error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_route_ids__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.RouteIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_route_allocations__ interface{}
		if __json_route_allocations__, _ok_ = _buf["route_allocations"]; !_ok_ || __json_route_allocations__ == nil {
			err = errors.New("route_allocations error")
			return
		} else {
			var __x__ map[string]int32
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok_ = (__json_route_allocations__).([]interface{}); !_ok_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make(map[string]int32)

				for _, _e0_ := range _arr0_ {
					var _kv0_ []interface{}
					if _kv0_, _ok0_ = _e0_.([]interface{}); !_ok0_ || len(_kv0_) != 2 {
						err = errors.New("__x__ error")
						return
					}
					var _key0_ string
					{
						if _key0_, _ok_ = _kv0_[0].(string); !_ok_ {
							err = errors.New("_key0_ error")
							return
						}
					}
					var _value0_ int32
					{
						var _ok_ bool
						var _x_ float64
						if _x_, _ok_ = _kv0_[1].(float64); !_ok_ {
							err = errors.New("_value0_ error")
							return
						}
						_value0_ = int32(_x_)
					}
					__x__[_key0_] = _value0_
				}
			}
			_v.RouteAllocations = __x__
		}
	}
	{
		var _ok_ bool
		var __json_scenario_ids__ interface{}
		if __json_scenario_ids__, _ok_ = _buf["scenario_ids"]; !_ok_ || __json_scenario_ids__ == nil {
			err = errors.New("scenario_ids error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_scenario_ids__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.ScenarioIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_map_tag_ids__ interface{}
		if __json_map_tag_ids__, _ok_ = _buf["map_tag_ids"]; !_ok_ || __json_map_tag_ids__ == nil {
			err = errors.New("map_tag_ids error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_map_tag_ids__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.MapTagIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_common_ct_setup_ids__ interface{}
		if __json_common_ct_setup_ids__, _ok_ = _buf["common_ct_setup_ids"]; !_ok_ || __json_common_ct_setup_ids__ == nil {
			err = errors.New("common_ct_setup_ids error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_common_ct_setup_ids__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.CommonCtSetupIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_success_next_phase__ interface{}
		if __json_success_next_phase__, _ok_ = _buf["success_next_phase"]; !_ok_ || __json_success_next_phase__ == nil {
			err = errors.New("success_next_phase error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_success_next_phase__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.SuccessNextPhase = __x__
		}
	}
	{
		var _ok_ bool
		var __json_failure_fallbacks__ interface{}
		if __json_failure_fallbacks__, _ok_ = _buf["failure_fallbacks"]; !_ok_ || __json_failure_fallbacks__ == nil {
			err = errors.New("failure_fallbacks error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_failure_fallbacks__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.FailureFallbacks = __x__
		}
	}
	return
}
