//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type Route struct {
	Id         string
	Name       string
	Side       string
	TargetSite string
	Nodes      []string
	MinPlayers int32
	MaxPlayers int32
	StyleTags  []string
}

const TypeId_Route = 79151657

func (*Route) GetTypeId() int32 {
	return 79151657
}

func NewRoute(_buf map[string]interface{}) (_v *Route, err error) {
	_v = &Route{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_name__ interface{}
		if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil {
			err = errors.New("name error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_name__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Name = __x__
		}
	}
	{
		var _ok_ bool
		var __json_side__ interface{}
		if __json_side__, _ok_ = _buf["side"]; !_ok_ || __json_side__ == nil {
			err = errors.New("side error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_side__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Side = __x__
		}
	}
	{
		var _ok_ bool
		var __json_target_site__ interface{}
		if __json_target_site__, _ok_ = _buf["target_site"]; !_ok_ || __json_target_site__ == nil {
			err = errors.New("target_site error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_target_site__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.TargetSite = __x__
		}
	}
	{
		var _ok_ bool
		var __json_nodes__ interface{}
		if __json_nodes__, _ok_ = _buf["nodes"]; !_ok_ || __json_nodes__ == nil {
			err = errors.New("nodes error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_nodes__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.Nodes = __x__
		}
	}
	{
		var _ok_ bool
		var __json_min_players__ interface{}
		if __json_min_players__, _ok_ = _buf["min_players"]; !_ok_ || __json_min_players__ == nil {
			err = errors.New("min_players error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_min_players__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.MinPlayers = __x__
		}
	}
	{
		var _ok_ bool
		var __json_max_players__ interface{}
		if __json_max_players__, _ok_ = _buf["max_players"]; !_ok_ || __json_max_players__ == nil {
			err = errors.New("max_players error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_max_players__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.MaxPlayers = __x__
		}
	}
	{
		var _ok_ bool
		var __json_style_tags__ interface{}
		if __json_style_tags__, _ok_ = _buf["style_tags"]; !_ok_ || __json_style_tags__ == nil {
			err = errors.New("style_tags error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_style_tags__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.StyleTags = __x__
		}
	}
	return
}
