
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type Scenario struct {
    Id string
    Route string
    Phase string
    Range string
    Site string
    Tempo string
    Posture string
    UtilityContext string
    MapTagIds []string
    BaseTimeCost int32
    BaseWeight int32
}

const TypeId_Scenario = -710944848

func (*Scenario) GetTypeId() int32 {
    return -710944848
}

func NewScenario(_buf map[string]interface{}) (_v *Scenario, err error) {
    _v = &Scenario{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_route__ interface{}; if __json_route__, _ok_ = _buf["route"]; !_ok_ || __json_route__ == nil { err = errors.New("route error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_route__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Route = __x__ }}
    { var _ok_ bool; var __json_phase__ interface{}; if __json_phase__, _ok_ = _buf["phase"]; !_ok_ || __json_phase__ == nil { err = errors.New("phase error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_phase__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Phase = __x__ }}
    { var _ok_ bool; var __json_range__ interface{}; if __json_range__, _ok_ = _buf["range"]; !_ok_ || __json_range__ == nil { err = errors.New("range error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_range__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Range = __x__ }}
    { var _ok_ bool; var __json_site__ interface{}; if __json_site__, _ok_ = _buf["site"]; !_ok_ || __json_site__ == nil { err = errors.New("site error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_site__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Site = __x__ }}
    { var _ok_ bool; var __json_tempo__ interface{}; if __json_tempo__, _ok_ = _buf["tempo"]; !_ok_ || __json_tempo__ == nil { err = errors.New("tempo error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_tempo__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Tempo = __x__ }}
    { var _ok_ bool; var __json_posture__ interface{}; if __json_posture__, _ok_ = _buf["posture"]; !_ok_ || __json_posture__ == nil { err = errors.New("posture error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_posture__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Posture = __x__ }}
    { var _ok_ bool; var __json_utility_context__ interface{}; if __json_utility_context__, _ok_ = _buf["utility_context"]; !_ok_ || __json_utility_context__ == nil { err = errors.New("utility_context error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_utility_context__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.UtilityContext = __x__ }}
    { var _ok_ bool; var __json_map_tag_ids__ interface{}; if __json_map_tag_ids__, _ok_ = _buf["map_tag_ids"]; !_ok_ || __json_map_tag_ids__ == nil { err = errors.New("map_tag_ids error"); return } else { var __x__ []string;  {
                    var _arr0_ []interface{}
                    var _ok0_ bool
                    if _arr0_, _ok0_ = (__json_map_tag_ids__).([]interface{}); !_ok0_ { err = errors.New("__x__ error"); return }
    
                    __x__ = make([]string, 0, len(_arr0_))
                    
                    for _, _e0_ := range _arr0_ {
                        var _list_v0_ string
                        {  if _list_v0_, _ok_ = _e0_.(string); !_ok_ { err = errors.New("_list_v0_ error"); return } }
                        __x__ = append(__x__, _list_v0_)
                    }
                }
    ; _v.MapTagIds = __x__ }}
    { var _ok_ bool; var __json_base_time_cost__ interface{}; if __json_base_time_cost__, _ok_ = _buf["base_time_cost"]; !_ok_ || __json_base_time_cost__ == nil { err = errors.New("base_time_cost error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_base_time_cost__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BaseTimeCost = __x__ }}
    { var _ok_ bool; var __json_base_weight__ interface{}; if __json_base_weight__, _ok_ = _buf["base_weight"]; !_ok_ || __json_base_weight__ == nil { err = errors.New("base_weight error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_base_weight__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.BaseWeight = __x__ }}
    return
}

