
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

type JsonLoader func(string) ([]map[string]interface{}, error)

type Tables struct {
    Tbitem *Tbitem
    TbPlayer *TbPlayer
}

func NewTables(loader JsonLoader) (*Tables, error) {
    var err error
    var buf []map[string]interface{}

    tables := &Tables{}
    if buf, err = loader("tbitem") ; err != nil {
        return nil, err
    }
    if tables.Tbitem, err = NewTbitem(buf) ; err != nil {
        return nil, err
    }
    if buf, err = loader("tbplayer") ; err != nil {
        return nil, err
    }
    if tables.TbPlayer, err = NewTbPlayer(buf) ; err != nil {
        return nil, err
    }
    return tables, nil
}


