//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbCombatConst struct {
	_dataMap  map[string]*CombatConst
	_dataList []*CombatConst
}

func NewTbCombatConst(_buf []map[string]interface{}) (*TbCombatConst, error) {
	_dataList := make([]*CombatConst, 0, len(_buf))
	dataMap := make(map[string]*CombatConst)

	for _, _ele_ := range _buf {
		if _v, err2 := NewCombatConst(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Key] = _v
		}
	}
	return &TbCombatConst{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbCombatConst) GetDataMap() map[string]*CombatConst {
	return table._dataMap
}

func (table *TbCombatConst) GetDataList() []*CombatConst {
	return table._dataList
}

func (table *TbCombatConst) Get(key string) *CombatConst {
	return table._dataMap[key]
}
