//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbEncounterModifier struct {
	_dataMap  map[string]*EncounterModifier
	_dataList []*EncounterModifier
}

func NewTbEncounterModifier(_buf []map[string]interface{}) (*TbEncounterModifier, error) {
	_dataList := make([]*EncounterModifier, 0, len(_buf))
	dataMap := make(map[string]*EncounterModifier)

	for _, _ele_ := range _buf {
		if _v, err2 := NewEncounterModifier(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbEncounterModifier{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbEncounterModifier) GetDataMap() map[string]*EncounterModifier {
	return table._dataMap
}

func (table *TbEncounterModifier) GetDataList() []*EncounterModifier {
	return table._dataList
}

func (table *TbEncounterModifier) Get(key string) *EncounterModifier {
	return table._dataMap[key]
}
