
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type Tbitem struct {
    _dataMap map[int32]*item
    _dataList []*item
}

func NewTbitem(_buf []map[string]interface{}) (*Tbitem, error) {
    _dataList := make([]*item, 0, len(_buf))
    dataMap := make(map[int32]*item)

    for _, _ele_ := range _buf {
        if _v, err2 := Newitem(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &Tbitem{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *Tbitem) GetDataMap() map[int32]*item {
    return table._dataMap
}

func (table *Tbitem) GetDataList() []*item {
    return table._dataList
}

func (table *Tbitem) Get(key int32) *item {
    return table._dataMap[key]
}


