
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TbMapNode struct {
    _dataMap map[string]*MapNode
    _dataList []*MapNode
}

func NewTbMapNode(_buf []map[string]interface{}) (*TbMapNode, error) {
    _dataList := make([]*MapNode, 0, len(_buf))
    dataMap := make(map[string]*MapNode)

    for _, _ele_ := range _buf {
        if _v, err2 := NewMapNode(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbMapNode{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbMapNode) GetDataMap() map[string]*MapNode {
    return table._dataMap
}

func (table *TbMapNode) GetDataList() []*MapNode {
    return table._dataList
}

func (table *TbMapNode) Get(key string) *MapNode {
    return table._dataMap[key]
}


