//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbMapTag struct {
	_dataMap  map[string]*MapTag
	_dataList []*MapTag
}

func NewTbMapTag(_buf []map[string]interface{}) (*TbMapTag, error) {
	_dataList := make([]*MapTag, 0, len(_buf))
	dataMap := make(map[string]*MapTag)

	for _, _ele_ := range _buf {
		if _v, err2 := NewMapTag(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbMapTag{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbMapTag) GetDataMap() map[string]*MapTag {
	return table._dataMap
}

func (table *TbMapTag) GetDataList() []*MapTag {
	return table._dataList
}

func (table *TbMapTag) Get(key string) *MapTag {
	return table._dataMap[key]
}
