
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TbMapEdge struct {
    _dataMap map[string]*MapEdge
    _dataList []*MapEdge
}

func NewTbMapEdge(_buf []map[string]interface{}) (*TbMapEdge, error) {
    _dataList := make([]*MapEdge, 0, len(_buf))
    dataMap := make(map[string]*MapEdge)

    for _, _ele_ := range _buf {
        if _v, err2 := NewMapEdge(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbMapEdge{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbMapEdge) GetDataMap() map[string]*MapEdge {
    return table._dataMap
}

func (table *TbMapEdge) GetDataList() []*MapEdge {
    return table._dataList
}

func (table *TbMapEdge) Get(key string) *MapEdge {
    return table._dataMap[key]
}


