//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbPlayer struct {
	_dataMap  map[string]*Player
	_dataList []*Player
}

func NewTbPlayer(_buf []map[string]interface{}) (*TbPlayer, error) {
	_dataList := make([]*Player, 0, len(_buf))
	dataMap := make(map[string]*Player)

	for _, _ele_ := range _buf {
		if _v, err2 := NewPlayer(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbPlayer{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbPlayer) GetDataMap() map[string]*Player {
	return table._dataMap
}

func (table *TbPlayer) GetDataList() []*Player {
	return table._dataList
}

func (table *TbPlayer) Get(key string) *Player {
	return table._dataMap[key]
}
