//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbRoute struct {
	_dataMap  map[string]*Route
	_dataList []*Route
}

func NewTbRoute(_buf []map[string]interface{}) (*TbRoute, error) {
	_dataList := make([]*Route, 0, len(_buf))
	dataMap := make(map[string]*Route)

	for _, _ele_ := range _buf {
		if _v, err2 := NewRoute(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbRoute{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbRoute) GetDataMap() map[string]*Route {
	return table._dataMap
}

func (table *TbRoute) GetDataList() []*Route {
	return table._dataList
}

func (table *TbRoute) Get(key string) *Route {
	return table._dataMap[key]
}
