//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbRouteTemplate struct {
	_dataMap  map[string]*RouteTemplate
	_dataList []*RouteTemplate
}

func NewTbRouteTemplate(_buf []map[string]interface{}) (*TbRouteTemplate, error) {
	_dataList := make([]*RouteTemplate, 0, len(_buf))
	dataMap := make(map[string]*RouteTemplate)

	for _, _ele_ := range _buf {
		if _v, err2 := NewRouteTemplate(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbRouteTemplate{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbRouteTemplate) GetDataMap() map[string]*RouteTemplate {
	return table._dataMap
}

func (table *TbRouteTemplate) GetDataList() []*RouteTemplate {
	return table._dataList
}

func (table *TbRouteTemplate) Get(key string) *RouteTemplate {
	return table._dataMap[key]
}
