//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbScenario struct {
	_dataMap  map[string]*Scenario
	_dataList []*Scenario
}

func NewTbScenario(_buf []map[string]interface{}) (*TbScenario, error) {
	_dataList := make([]*Scenario, 0, len(_buf))
	dataMap := make(map[string]*Scenario)

	for _, _ele_ := range _buf {
		if _v, err2 := NewScenario(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbScenario{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbScenario) GetDataMap() map[string]*Scenario {
	return table._dataMap
}

func (table *TbScenario) GetDataList() []*Scenario {
	return table._dataList
}

func (table *TbScenario) Get(key string) *Scenario {
	return table._dataMap[key]
}
