//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbTeam struct {
	_dataMap  map[string]*Team
	_dataList []*Team
}

func NewTbTeam(_buf []map[string]interface{}) (*TbTeam, error) {
	_dataList := make([]*Team, 0, len(_buf))
	dataMap := make(map[string]*Team)

	for _, _ele_ := range _buf {
		if _v, err2 := NewTeam(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbTeam{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbTeam) GetDataMap() map[string]*Team {
	return table._dataMap
}

func (table *TbTeam) GetDataList() []*Team {
	return table._dataList
}

func (table *TbTeam) Get(key string) *Team {
	return table._dataMap[key]
}
