//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

type TbTutorialBattle struct {
	_dataMap  map[string]*TutorialBattle
	_dataList []*TutorialBattle
}

func NewTbTutorialBattle(_buf []map[string]interface{}) (*TbTutorialBattle, error) {
	_dataList := make([]*TutorialBattle, 0, len(_buf))
	dataMap := make(map[string]*TutorialBattle)

	for _, _ele_ := range _buf {
		if _v, err2 := NewTutorialBattle(_ele_); err2 != nil {
			return nil, err2
		} else {
			_dataList = append(_dataList, _v)
			dataMap[_v.Id] = _v
		}
	}
	return &TbTutorialBattle{_dataList: _dataList, _dataMap: dataMap}, nil
}

func (table *TbTutorialBattle) GetDataMap() map[string]*TutorialBattle {
	return table._dataMap
}

func (table *TbTutorialBattle) GetDataList() []*TutorialBattle {
	return table._dataList
}

func (table *TbTutorialBattle) Get(key string) *TutorialBattle {
	return table._dataMap[key]
}
