
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type TbVisibility struct {
    _dataMap map[string]*Visibility
    _dataList []*Visibility
}

func NewTbVisibility(_buf []map[string]interface{}) (*TbVisibility, error) {
    _dataList := make([]*Visibility, 0, len(_buf))
    dataMap := make(map[string]*Visibility)

    for _, _ele_ := range _buf {
        if _v, err2 := NewVisibility(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.Id] = _v
        }
    }
    return &TbVisibility{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *TbVisibility) GetDataMap() map[string]*Visibility {
    return table._dataMap
}

func (table *TbVisibility) GetDataList() []*Visibility {
    return table._dataList
}

func (table *TbVisibility) Get(key string) *Visibility {
    return table._dataMap[key]
}


