//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type Team struct {
	Id        string
	Name      string
	ShortName string
	Nickname  string
	Logo      string
}

const TypeId_Team = 2602621

func (*Team) GetTypeId() int32 {
	return 2602621
}

func NewTeam(_buf map[string]interface{}) (_v *Team, err error) {
	_v = &Team{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_name__ interface{}
		if __json_name__, _ok_ = _buf["name"]; !_ok_ || __json_name__ == nil {
			err = errors.New("name error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_name__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Name = __x__
		}
	}
	{
		var _ok_ bool
		var __json_shortName__ interface{}
		if __json_shortName__, _ok_ = _buf["shortName"]; !_ok_ || __json_shortName__ == nil {
			err = errors.New("shortName error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_shortName__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.ShortName = __x__
		}
	}
	{
		var _ok_ bool
		var __json_nickname__ interface{}
		if __json_nickname__, _ok_ = _buf["nickname"]; !_ok_ || __json_nickname__ == nil {
			err = errors.New("nickname error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_nickname__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Nickname = __x__
		}
	}
	{
		var _ok_ bool
		var __json_logo__ interface{}
		if __json_logo__, _ok_ = _buf["logo"]; !_ok_ || __json_logo__ == nil {
			err = errors.New("logo error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_logo__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Logo = __x__
		}
	}
	return
}
