//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg

import "errors"

type TutorialBattle struct {
	Id                string
	Version           int32
	Enabled           bool
	Budget            int32
	RosterSize        int32
	MapId             string
	Tier5PlayerIds    []string
	Tier4PlayerIds    []string
	Tier3PlayerIds    []string
	Tier2PlayerIds    []string
	Tier1PlayerIds    []string
	OpponentTeamId    string
	OpponentPlayerIds []string
}

const TypeId_TutorialBattle = -424233514

func (*TutorialBattle) GetTypeId() int32 {
	return -424233514
}

func NewTutorialBattle(_buf map[string]interface{}) (_v *TutorialBattle, err error) {
	_v = &TutorialBattle{}
	{
		var _ok_ bool
		var __json_id__ interface{}
		if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil {
			err = errors.New("id error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_id__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Id = __x__
		}
	}
	{
		var _ok_ bool
		var __json_version__ interface{}
		if __json_version__, _ok_ = _buf["version"]; !_ok_ || __json_version__ == nil {
			err = errors.New("version error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_version__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Version = __x__
		}
	}
	{
		var _ok_ bool
		var __json_enabled__ interface{}
		if __json_enabled__, _ok_ = _buf["enabled"]; !_ok_ || __json_enabled__ == nil {
			err = errors.New("enabled error")
			return
		} else {
			var __x__ bool
			{
				var _ok_ bool
				if __x__, _ok_ = __json_enabled__.(bool); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.Enabled = __x__
		}
	}
	{
		var _ok_ bool
		var __json_budget__ interface{}
		if __json_budget__, _ok_ = _buf["budget"]; !_ok_ || __json_budget__ == nil {
			err = errors.New("budget error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_budget__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.Budget = __x__
		}
	}
	{
		var _ok_ bool
		var __json_rosterSize__ interface{}
		if __json_rosterSize__, _ok_ = _buf["rosterSize"]; !_ok_ || __json_rosterSize__ == nil {
			err = errors.New("rosterSize error")
			return
		} else {
			var __x__ int32
			{
				var _ok_ bool
				var _x_ float64
				if _x_, _ok_ = __json_rosterSize__.(float64); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
				__x__ = int32(_x_)
			}
			_v.RosterSize = __x__
		}
	}
	{
		var _ok_ bool
		var __json_mapId__ interface{}
		if __json_mapId__, _ok_ = _buf["mapId"]; !_ok_ || __json_mapId__ == nil {
			err = errors.New("mapId error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_mapId__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.MapId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_tier5PlayerIds__ interface{}
		if __json_tier5PlayerIds__, _ok_ = _buf["tier5PlayerIds"]; !_ok_ || __json_tier5PlayerIds__ == nil {
			err = errors.New("tier5PlayerIds error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_tier5PlayerIds__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.Tier5PlayerIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_tier4PlayerIds__ interface{}
		if __json_tier4PlayerIds__, _ok_ = _buf["tier4PlayerIds"]; !_ok_ || __json_tier4PlayerIds__ == nil {
			err = errors.New("tier4PlayerIds error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_tier4PlayerIds__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.Tier4PlayerIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_tier3PlayerIds__ interface{}
		if __json_tier3PlayerIds__, _ok_ = _buf["tier3PlayerIds"]; !_ok_ || __json_tier3PlayerIds__ == nil {
			err = errors.New("tier3PlayerIds error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_tier3PlayerIds__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.Tier3PlayerIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_tier2PlayerIds__ interface{}
		if __json_tier2PlayerIds__, _ok_ = _buf["tier2PlayerIds"]; !_ok_ || __json_tier2PlayerIds__ == nil {
			err = errors.New("tier2PlayerIds error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_tier2PlayerIds__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.Tier2PlayerIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_tier1PlayerIds__ interface{}
		if __json_tier1PlayerIds__, _ok_ = _buf["tier1PlayerIds"]; !_ok_ || __json_tier1PlayerIds__ == nil {
			err = errors.New("tier1PlayerIds error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_tier1PlayerIds__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.Tier1PlayerIds = __x__
		}
	}
	{
		var _ok_ bool
		var __json_opponentTeamId__ interface{}
		if __json_opponentTeamId__, _ok_ = _buf["opponentTeamId"]; !_ok_ || __json_opponentTeamId__ == nil {
			err = errors.New("opponentTeamId error")
			return
		} else {
			var __x__ string
			{
				if __x__, _ok_ = __json_opponentTeamId__.(string); !_ok_ {
					err = errors.New("__x__ error")
					return
				}
			}
			_v.OpponentTeamId = __x__
		}
	}
	{
		var _ok_ bool
		var __json_opponentPlayerIds__ interface{}
		if __json_opponentPlayerIds__, _ok_ = _buf["opponentPlayerIds"]; !_ok_ || __json_opponentPlayerIds__ == nil {
			err = errors.New("opponentPlayerIds error")
			return
		} else {
			var __x__ []string
			{
				var _arr0_ []interface{}
				var _ok0_ bool
				if _arr0_, _ok0_ = (__json_opponentPlayerIds__).([]interface{}); !_ok0_ {
					err = errors.New("__x__ error")
					return
				}

				__x__ = make([]string, 0, len(_arr0_))

				for _, _e0_ := range _arr0_ {
					var _list_v0_ string
					{
						if _list_v0_, _ok_ = _e0_.(string); !_ok_ {
							err = errors.New("_list_v0_ error")
							return
						}
					}
					__x__ = append(__x__, _list_v0_)
				}
			}
			_v.OpponentPlayerIds = __x__
		}
	}
	return
}
