
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type Visibility struct {
    Id string
    FromNode string
    ToNode string
    Visible bool
    Range string
    AngleAdvantage string
    Elevation string
    CoverModifier int32
    ExposureModifier int32
}

const TypeId_Visibility = -360169678

func (*Visibility) GetTypeId() int32 {
    return -360169678
}

func NewVisibility(_buf map[string]interface{}) (_v *Visibility, err error) {
    _v = &Visibility{}
    { var _ok_ bool; var __json_id__ interface{}; if __json_id__, _ok_ = _buf["id"]; !_ok_ || __json_id__ == nil { err = errors.New("id error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_id__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Id = __x__ }}
    { var _ok_ bool; var __json_from_node__ interface{}; if __json_from_node__, _ok_ = _buf["from_node"]; !_ok_ || __json_from_node__ == nil { err = errors.New("from_node error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_from_node__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.FromNode = __x__ }}
    { var _ok_ bool; var __json_to_node__ interface{}; if __json_to_node__, _ok_ = _buf["to_node"]; !_ok_ || __json_to_node__ == nil { err = errors.New("to_node error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_to_node__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.ToNode = __x__ }}
    { var _ok_ bool; var __json_visible__ interface{}; if __json_visible__, _ok_ = _buf["visible"]; !_ok_ || __json_visible__ == nil { err = errors.New("visible error"); return } else { var __x__ bool;  { var _ok_ bool; if __x__, _ok_ = __json_visible__.(bool); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Visible = __x__ }}
    { var _ok_ bool; var __json_range__ interface{}; if __json_range__, _ok_ = _buf["range"]; !_ok_ || __json_range__ == nil { err = errors.New("range error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_range__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Range = __x__ }}
    { var _ok_ bool; var __json_angle_advantage__ interface{}; if __json_angle_advantage__, _ok_ = _buf["angle_advantage"]; !_ok_ || __json_angle_advantage__ == nil { err = errors.New("angle_advantage error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_angle_advantage__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.AngleAdvantage = __x__ }}
    { var _ok_ bool; var __json_elevation__ interface{}; if __json_elevation__, _ok_ = _buf["elevation"]; !_ok_ || __json_elevation__ == nil { err = errors.New("elevation error"); return } else { var __x__ string;  {  if __x__, _ok_ = __json_elevation__.(string); !_ok_ { err = errors.New("__x__ error"); return } }; _v.Elevation = __x__ }}
    { var _ok_ bool; var __json_cover_modifier__ interface{}; if __json_cover_modifier__, _ok_ = _buf["cover_modifier"]; !_ok_ || __json_cover_modifier__ == nil { err = errors.New("cover_modifier error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_cover_modifier__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.CoverModifier = __x__ }}
    { var _ok_ bool; var __json_exposure_modifier__ interface{}; if __json_exposure_modifier__, _ok_ = _buf["exposure_modifier"]; !_ok_ || __json_exposure_modifier__ == nil { err = errors.New("exposure_modifier error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_exposure_modifier__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.ExposureModifier = __x__ }}
    return
}

