/**
 * Config table loader module
 * Auto-generated by Luban; do not modify schema.ts manually.
 */

export { Tables, Tbitem, item } from './schema';

const TABLE_NAMES = ['tbitem'];

export async function loadConfig(): Promise<InstanceType<typeof Tables>> {
  const { Tables } = await import('./schema');

  const dataCache: Record<string, unknown> = {};

  await Promise.all(
    TABLE_NAMES.map(async (name) => {
      const resp = await fetch(`/data/config/${name}.json`);
      if (!resp.ok) {
        throw new Error(`Failed to load config table "${name}": ${resp.status}`);
      }
      dataCache[name] = await resp.json();
    })
  );

  const loader = (tableName: string) => {
    const data = dataCache[tableName];
    if (!data) throw new Error(`Config table "${tableName}" not found`);
    return data;
  };

  return new Tables(loader);
}
