/**
 * Config table loader module
 * Auto-generated by Luban; do not modify schema.ts manually.
 */

export * from './schema';
import { Tables } from './schema';

const TABLE_NAMES = [
  'tbcombatconst', 'tbencountermodifier', 'tbitem', 'tbmapedge', 'tbmapnode',
  'tbmaptag', 'tbplayer', 'tbroute', 'tbroutetemplate', 'tbscenario', 'tbteam',
  'tbtutorialbattle', 'tbvisibility',
];

export async function loadConfig(): Promise<InstanceType<typeof Tables>> {
  const dataCache: Record<string, unknown> = {};

  await Promise.all(
    TABLE_NAMES.map(async (name) => {
      const resp = await fetch(`/data/config/${name}.json`);
      if (!resp.ok) {
        throw new Error(`Failed to load config table "${name}": ${resp.status}`);
      }
      dataCache[name] = await resp.json();
    })
  );

  const loader = (tableName: string) => {
    const data = dataCache[tableName];
    if (!data) throw new Error(`Config table "${tableName}" not found`);
    return data;
  };

  return new Tables(loader);
}
