
// @ts-nocheck
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------







export class item {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.price === undefined) { throw new Error() }
        this.price = _json_.price
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 价格
     */
    readonly price: number

    resolve(tables:Tables) {
        
        
        
        
    }
}






export class Tbitem {
    private _dataMap: Map<number, item>
    private _dataList: item[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, item>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: item
            _v = new item(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, item> { return this._dataMap; }
    getDataList(): item[] { return this._dataList; }

    get(key: number): item | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




type JsonLoader = (file: string) => any

export class Tables {
    private _Tbitem: Tbitem
    get Tbitem(): Tbitem  { return this._Tbitem;}

    constructor(loader: JsonLoader) {
        this._Tbitem = new Tbitem(loader('tbitem'))

        this._Tbitem.resolve(this)
    }
}

