// @ts-nocheck

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------







export class item {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.desc === undefined) { throw new Error() }
        this.desc = _json_.desc
        if (_json_.price === undefined) { throw new Error() }
        this.price = _json_.price
    }

    /**
     * id
     */
    readonly id: number
    /**
     * 名称
     */
    readonly name: string
    /**
     * 描述
     */
    readonly desc: string
    /**
     * 价格
     */
    readonly price: number

    resolve(tables:Tables) {
        
        
        
        
    }
}





export class Player {

    constructor(_json_: any) {
        if (_json_.id === undefined) { throw new Error() }
        this.id = _json_.id
        if (_json_.name === undefined) { throw new Error() }
        this.name = _json_.name
        if (_json_.team === undefined) { throw new Error() }
        this.team = _json_.team
        if (_json_.nationality === undefined) { throw new Error() }
        this.nationality = _json_.nationality
        if (_json_.entry === undefined) { throw new Error() }
        this.entry = _json_.entry
        if (_json_.aim === undefined) { throw new Error() }
        this.aim = _json_.aim
        if (_json_.trade === undefined) { throw new Error() }
        this.trade = _json_.trade
        if (_json_.clutch === undefined) { throw new Error() }
        this.clutch = _json_.clutch
        if (_json_.firepower === undefined) { throw new Error() }
        this.firepower = _json_.firepower
        if (_json_.gamesense === undefined) { throw new Error() }
        this.gamesense = _json_.gamesense
        if (_json_.positions === undefined) { throw new Error() }
        { this.positions = []; for(let _ele0 of _json_.positions) { let _e0; _e0 = _ele0; this.positions.push(_e0);}}
        if (_json_.rarity === undefined) { throw new Error() }
        this.rarity = _json_.rarity
        if (_json_.portrait === undefined) { throw new Error() }
        this.portrait = _json_.portrait
    }

    /**
     * 选手ID
     */
    readonly id: string
    /**
     * 显示名称
     */
    readonly name: string
    /**
     * 所属战�?     */
    readonly team: string
    /**
     * 国籍
     */
    readonly nationality: string
    /**
     * 突破
     */
    readonly entry: number
    /**
     * 精准
     */
    readonly aim: number
    /**
     * 补枪
     */
    readonly trade: number
    /**
     * 残局
     */
    readonly clutch: number
    /**
     * 火力
     */
    readonly firepower: number
    /**
     * 意识
     */
    readonly gamesense: number
    /**
     * 位置标签
     */
    readonly positions: string[]
    /**
     * 稀有度
     */
    readonly rarity: string
    /**
     * 头像路径
     */
    readonly portrait: string

    resolve(tables:Tables) {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
}






export class Tbitem {
    private _dataMap: Map<number, item>
    private _dataList: item[]
    constructor(_json_: any) {
        this._dataMap = new Map<number, item>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: item
            _v = new item(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<number, item> { return this._dataMap; }
    getDataList(): item[] { return this._dataList; }

    get(key: number): item | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




export class TbPlayer {
    private _dataMap: Map<string, Player>
    private _dataList: Player[]
    constructor(_json_: any) {
        this._dataMap = new Map<string, Player>()
        this._dataList = []
        for(var _json2_ of _json_) {
            let _v: Player
            _v = new Player(_json2_)
            this._dataList.push(_v)
            this._dataMap.set(_v.id, _v)
        }
    }

    getDataMap(): Map<string, Player> { return this._dataMap; }
    getDataList(): Player[] { return this._dataList; }

    get(key: string): Player | undefined { return this._dataMap.get(key); }

    resolve(tables:Tables) {
        for(let  data of this._dataList)
        {
            data.resolve(tables)
        }
    }

}




type JsonLoader = (file: string) => any

export class Tables {
    private _Tbitem: Tbitem
    get Tbitem(): Tbitem  { return this._Tbitem;}
    private _TbPlayer: TbPlayer
    get TbPlayer(): TbPlayer  { return this._TbPlayer;}

    constructor(loader: JsonLoader) {
        this._Tbitem = new Tbitem(loader('tbitem'))
        this._TbPlayer = new TbPlayer(loader('tbplayer'))

        this._Tbitem.resolve(this)
        this._TbPlayer.resolve(this)
    }
}


